### ISSUE TITLE
知识库附件上传文档时出现错误

### ISSUE THREAD

**Issue by AlexWeiCD** [hkh1012/langchain-springboot#3]
错误信息如下：
Unable to make field private final sun.net.www.protocol.https.DelegateHttpsURLConnection sun.net.www.protocol.https.HttpsURLConnectionImpl.delegate accessible: module java.base does not "opens sun.net.www.protocol.https" to unnamed module @761e065f

**Comment by hkh1012** [comment]
已修复.
